# k8s master join

---
  - hosts: master1
    become: yes
    vars_files:
    - env_variables
    tasks:
    - name: Setup the hostname
      shell: hostnamectl set-hostname {{ hostname[2] }}

    - name: Make Hostname persist.
      copy:
        dest: "/etc/cloud/cloud.cfg.d/99_hostname.cfg"
        content: |
          preserve_hostname: true

    - name: Create a second loopback interface.
      copy:
        dest: "/etc/sysconfig/network-scripts/ifcfg-lo:1"
        content: |
          DEVICE=lo:1
          IPADDR={{ masters[1] }}
          NETMASK=255.255.255.255
          NETWORK=127.0.0.0
          BROADCAST=127.255.255.255
          ONBOOT=yes
          NAME=loopback

    - name: Restart network
      shell: systemctl restart network

    - name: Point DNS to our server
      shell: echo "nameserver 10.42.0.241" > /etc/resolv.conf

    - name: Enable the module for cluster communication.
      shell: sysctl --system

    - name: Enabling Bridge Firewall Rule
      shell: "echo '1' > /proc/sys/net/ipv4/ip_forward"

    - name: Copying token to worker node
      copy: src={{ token_file }} dest="/home/centos/join_token"

    - name: Gather Kubeadm command 
      shell: cat join_token | tail -12 | head -3 > /home/centos/join.sh
        
    - name: Add apiserver IP to the join command
      lineinfile:
        path: /home/centos/join.sh
        line: --apiserver-advertise-address={{ masters[1] }} \
        insertbefore: '--control'
    
    - name: Resetting kubeadm
      shell: kubeadm reset -f

    - name: Join the master
      shell: sh join.sh    
